/**
 * USER ACTIONS
 */
export const FETCHING_USER = 'FETCHING_USER';
export const FETCHING_USER_SUCCESS = 'FETCHING_USER_SUCCESS';
export const FETCHING_USER_FAIL = 'FETCHING_USER_FAIL';
export const UPDATING_USER = 'UPDATING_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';

export const RESET_STATE = 'RESET_STATE';
export const CLEAR_STATE = 'CLEAR_STATE';

// Notifications
export const FETCHING_NOTIFICATIONS = 'FETCHING_NOTIFICATIONS';
export const FETCHING_NOTIFICATIONS_SUCCESS = 'FETCHING_NOTIFICATIONS_SUCCESS';
export const FETCHING_NOTIFICATIONS_FAIL = 'FETCHING_NOTIFICATIONS_FAIL';
export const UPDATING_NOTIFICATIONS = 'UPDATING_NOTIFICATIONS';
export const UPDATING_NOTIFICATIONS_SUCCESS = 'UPDATING_NOTIFICATIONS_SUCCESS';
export const UPDATING_NOTIFICATIONS_FAIL = 'UPDATING_NOTIFICATIONS_FAIL';
